[profile.default]
src = "src"
test = "test"
out = "out"
libs = []
solc = "0.8.0"
remappings = ["@openzeppelin/contracts/=src/"]
optimizer = true
optimizer_runs = 200

[invariant]
runs = 200
depth = 120
fail_on_revert = false
call_override = false
